Error: Oops! Cannot create the reference grid. (#841)
* Error: Oops! Cannot create the reference grid.
Fixes #839

* add test

* version

* update news

* add model_parameters method, for nicer print

* Apply automatic changes

* Revert "Apply automatic changes"

This reverts commit 7d33ebfe6c4dc91e413945f2f5df8d25954a5e14.

* fix test

* Apply automatic changes

* Revert "Apply automatic changes"

This reverts commit da1cb14144aef75c7b11cbfef84a5147426c17c7.

* Apply automatic changes

Co-authored-by: strengejacke <strengejacke@users.noreply.github.com>